version = 0.1
[default.deploy.parameters]
stack_name = "BetterWellness"
resolve_s3 = true
s3_prefix = "BetterWellness"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"dev\" S3BucketName=\"better-wellness-ui\" CognitoUserPoolName=\"better-wellness-userpool\" CognitoWebClientName=\"better-wellness-webclient\""
image_repositories = []
